### ISSUE TITLE
SEO Needs Fixing

### ISSUE THREAD

**Issue by TCROC** [crablang/crablang-site#8]
![image](https://user-images.githubusercontent.com/24307049/232339213-ebd6d5b1-5a39-4571-843d-92d2d05c439f.png)

When searching "crablang", all I get is reddit, the GitHub repo (which is good), and something else below.  crablang.org is not appearing.

**Comment by trvswgnr** [comment]
seems to be showing up now. probably just needed some time and traffic.
SEO can surely still be improved (also not sure why it's showing the astro favicon), but going to close this for now.
<br>
<img src="https://user-images.githubusercontent.com/8974888/233162783-90062480-f007-4f1a-9e02-f546ae051b5c.png" width="500">

**Comment by TCROC** [comment]
it sure is!

![image](https://user-images.githubusercontent.com/24307049/233163289-95f32ce5-85eb-4f33-8b1c-3d1053d2bc38.png)
